## Developer option, set to false if GoodestEnglish didn't tell you to set to true
debug: false
## MongoDB login information
mongo:
  uri-mode: false
  normal:
    host: 127.0.0.1
    port: 27017
    auth:
      enabled: false
      username: ''
      password: ''
  uri:
    database: Practice
    connection-string: mongodb://127.0.0.1:27017/Eden
## Toggle if the fancy tablist should be enabled or not
fancy-tablist: true
nametag:
  ## Toggle if the plugin should modify the nametag color or not
  enabled: true
  ## What color should the nametag be when the player is in lobby?
  ## Check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html for available colors
  color: BLUE
party:
  ## When player creates a party, what is the default size?
  default-max-size: 30
lobby:
  ## Should player allow to see other players?
  display-players: false
match:
  ## If points are enabled, how many points should it be?
  maximum-points: 3
  goal-portal-protect-radius: 3
  ## Right now boxing will count hit as 2 hits if player is spam clicking and jumping (critical hits)
  ## This option will change paperspigot's config 'disable-player-crits' to true. So crit hit will not be exists anymore.
  ## Warning: This option will disable crit damage, and will change and save paperspigot's 'disable-player-crits' settings
  fix-hit-count-error: true
## These options will only works if you are using ImanitySpigot
## If you are not using, then turn every imanity related settings off
imanity:
  teleport-async: true