## Developer option, set to false if GoodestEnglish didn't tell you to set to true
debug: false
## Should arena and kit auto save after you make a changes?
## If auto save is disabled, you have to use command '/kit save <Kit Name>' or '/arena save <Arena Name>' to save them manually
## NOTE: Auto save will save each process after you made a changes into arena and kit, and changes are final (which means it cannot be reverted) if you set this to true
arena-kit-auto-save: false
## MongoDB login information
mongo:
  ## This option should be ALWAYS true. Unless you want to test specific stuff without modifying the database
  ## If it is disabled, player stats will not be loaded and saved
  enabled: true
  uri-mode: false
  normal:
    host: 127.0.0.1
    port: 27017
    auth:
      enabled: false
      username: ''
      password: ''
  uri:
    database: Practice
    connection-string: mongodb://127.0.0.1:27017/Eden
## Built-in tablist editor
## Note that some user might experience tablist column incorrectly format. If that happens, please do not use this tablist function
fancy-tablist:
  ## Toggle if the fancy tablist should be enabled or not
  enabled: true
  ## How should each tab element shown
  ## This supports PlaceholderAPI, so if you wish to show player prefix, you can do it!
  format: "&a{player-name}"
  ## The ticks of how often the tablist will be updated
  ## Default is 20, which is 1 second. 1 tick is equal to 0.05 second
  update-ticks: 20
nametag:
  ## Toggle if the plugin should modify the nametag color or not
  enabled: true
  ## What color should the nametag be when the player is in lobby?
  ## Check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html for available colors
  color: BLUE
party:
  ## When player creates a party, what is the default size?
  default-max-size: 30
lobby:
  ## Should player allow to see other players?
  display-players: false
match:
  ## Right now boxing will count hit as 2 hits if player is spam clicking and jumping (critical hits)
  ## This option will change paperspigot's config 'disable-player-crits' to true. So crit hit will not be exists anymore.
  ## Warning: This option will disable crit damage, and will change and save paperspigot's 'disable-player-crits' settings
  fix-hit-count-error: true
  ## Should snow block be removed when the snowball hit the object?
  ## Set to true if you wish to remove the object (which is the snow block)
  remove-snow-block-when-snowball-hit: false
  ## When player consume a golden apple, should the system gives normal effects to the player (which contains instantly regenerate to full health, saturation and absorption hearts), or just regenerate to full health?
  ## Default is false which only set the player health to full, no effects are given
  instant-gapple-effects: false
  ## Titles - Which type of title should be shown?
  title:
    ## Shows title when someone scores a point?
    score: true
    ## Shows title when the match has a result?
    end: true
  ## The ticks which represents between from match ends to send the player to lobby and reset the arena
  ## 20 ticks is 1 second, so if 100 ticks then it will be 5 seconds
  ## Default is 100, and is recommended. Change this value with caution
  end-duration: 100
## Simple chat format
chat-format:
  ## Set this to true if you want to enable chat format
  enabled: true
  ## What is the format should be? (This supports PlaceholderAPI)
  ## Use %1$s for player's name and %2$s for player's message
  format: "&a%1$s&f: %2$s"
## These options will only works if you are using ImanitySpigot
## If you are not using, then turn every imanity related settings off
imanity:
  teleport-async: true