main: rip.diamond.practice.Eden
name: Eden
version: '${version}'
author: GoodestEnglish
description: The best practice plugin with premium features
website: https://youtube.com/c/goodestenglishpvp
depend: [WorldEdit, FastAsyncWorldEdit, ProtocolLib]
softdepend: [ViaVersion, PlaceholderAPI, Citizens]